In [ ]:
import json

In [ ]:
with open('para.txt', 'r') as fp:
    para = json.load(fp)

In [ ]:
globals().update(para)

In [12]:
import pandas_datareader.data as web

In [13]:
symbol = 'WIKI/AAPL'  # or 'AAPL.US'

In [19]:
import os

os.environ['QUANDL_API_KEY'] = quandl_api

In [22]:
df = web.DataReader(symbol, 'quandl', '2015-01-01', '2015-01-05')

In [23]:
df

,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,
2015-01-05,108.29,108.65,105.41,106.25,64285491.0,0.0,1.0,102.875953,103.217954,100.139941,100.937944,64285491.0
2015-01-02,111.39,111.44,107.35,109.33,53204626.0,0.0,1.0,105.820966,105.868466,101.982949,103.863957,53204626.0

In [28]:
df = web.DataReader(symbol, 'quandl', '2015-01-01', '2019-02-28')

In [27]:
df

,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,
2018-03-27,173.680,175.1500,166.9200,168.340,38962839.0,0.00,1.0,173.680000,175.150000,166.920000,168.340000,38962839.0
2018-03-26,168.070,173.1000,166.4400,172.770,36272617.0,0.00,1.0,168.070000,173.100000,166.440000,172.770000,36272617.0
2018-03-23,168.390,169.9200,164.9400,164.940,40248954.0,0.00,1.0,168.390000,169.920000,164.940000,164.940000,40248954.0
2018-03-22,170.000,172.6800,168.6000,168.845,41051076.0,0.00,1.0,170.000000,172.680000,168.600000,168.845000,41051076.0
2018-03-21,175.040,175.0900,171.2600,171.270,35247358.0,0.00,1.0,175.040000,175.090000,171.260000,171.270000,35247358.0
2018-03-20,175.240,176.8000,174.9400,175.240,19314039.0,0.00,1.0,175.240000,176.800000,174.940000,175.240000,19314039.0
2018-03-19,177.320,177.4700,173.6600,175.300,32804695.0,0.00,1.0,177.320000,177.470000,173.660000,175.300000,32804695.0
2018-03-16,178.650,179.1200,177.6200,178.020,36836456.0,0.00,1.0,178.650000,179.120000,177.620000,178.020000,36836456.0
2018-03-15,178.500,180.2400,178.0701,178.650,22584565.0,0.00,1.0,178.500000,180.240000,178.070100,178.650000,22584565.0
2018-03-14,180.320,180.5200,177.8100,178.440,29075469.0,0.00,1.0,180.320000,180.520000,177.810000,178.440000,29075469.0
2018-03-13,182.590,183.5000,179.2400,179.970,31168404.0,0.00,1.0,182.590000,183.500000,179.240000,179.970000,31168404.0
2018-03-12,180.290,182.3900,180.2100,181.720,32055405.0,0.00,1.0,180.290000,182.390000,180.210000,181.720000,32055405.0
2018-03-09,177.960,180.0000,177.3900,179.980,31385134.0,0.00,1.0,177.960000,180.000000,177.390000,179.980000,31385134.0
2018-03-08,175.480,177.1200,175.0700,176.940,23163767.0,0.00,1.0,175.480000,177.120000,175.070000,176.940000,23163767.0
2018-03-07,174.940,175.8500,174.2700,175.030,31703462.0,0.00,1.0,174.940000,175.850000,174.270000,175.030000,31703462.0
2018-03-06,177.910,178.2500,176.1300,176.670,23788506.0,0.00,1.0,177.910000,178.250000,176.130000,176.670000,23788506.0
2018-03-05,175.210,177.7400,174.5200,176.820,28401366.0,0.00,1.0,175.210000,177.740000,174.520000,176.820000,28401366.0
2018-03-02,172.800,176.3000,172.4500,176.210,38453950.0,0.00,1.0,172.800000,176.300000,172.450000,176.210000,38453950.0
2018-03-01,178.540,179.7750,172.6600,175.000,48801970.0,0.00,1.0,178.540000,179.775000,172.660000,175.000000,48801970.0
2018-02-28,179.260,180.6150,178.0500,178.120,33604574.0,0.00,1.0,179.260000,180.615000,178.050000,178.120000,33604574.0
2018-02-27,179.100,180.4800,178.1600,178.390,38685165.0,0.00,1.0,179.100000,180.480000,178.160000,178.390000,38685165.0
2018-02-26,176.350,179.3900,176.2100,178.970,36886432.0,0.00,1.0,176.350000,179.390000,176.210000,178.970000,36886432.0
2018-02-23,173.670,175.6500,173.5400,175.555,33329232.0,0.00,1.0,173.670000,175.650000,173.540000,175.555000,33329232.0
2018-02-22,171.800,173.9500,171.7100,172.600,30504116.0,0.00,1.0,171.800000,173.950000,171.710000,172.600000,30504116.0
2018-02-21,172.830,174.1200,171.0100,171.070,35833514.0,0.00,1.0,172.830000,174.120000,171.010000,171.070000,35833514.0
2018-02-20,172.050,174.2600,171.4200,171.850,33531012.0,0.00,1.0,172.050000,174.260000,171.420000,171.850000,33531012.0
2018-02-16,172.360,174.8200,171.7700,172.430,39638793.0,0.00,1.0,172.360000,174.820000,171.770000,172.430000,39638793.0
2018-02-15,169.790,173.0900,169.0000,172.990,50609595.0,0.00,1.0,169.790000,173.090000,169.000000,172.990000,50609595.0
2018-02-14,163.045,167.5400,162.8800,167.370,39669178.0,0.00,1.0,163.045000,167.540000,162.880000,167.370000,39669178.0
2018-02-13,161.950,164.7500,161.6500,164.340,32104756.0,0.00,1.0,161.950000,164.750000,161.650000,164.340000,32104756.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2015-02-13,127.280,127.2800,125.6500,127.080,54272219.0,0.00,1.0,121.390359,121.390359,119.835784,121.199614,54272219.0
2015-02-12,126.060,127.4800,125.5700,126.460,74474466.0,0.00,1.0,120.226812,121.581104,119.759486,120.608303,74474466.0
2015-02-11,122.770,124.9200,122.5000,124.880,73561797.0,0.00,1.0,117.089051,119.139564,116.831544,119.101414,73561797.0
2015-02-10,120.170,122.1500,120.1600,122.020,62008506.0,0.00,1.0,114.609361,116.497740,114.599823,116.373756,62008506.0
2015-02-09,118.550,119.8400,118.4300,119.720,38889797.0,0.00,1.0,113.064323,114.294631,112.949876,114.180184,38889797.0
2015-02-06,120.020,120.2500,118.4500,118.930,43706567.0,0.00,1.0,114.466302,114.685659,112.968951,113.426739,43706567.0
2015-02-05,120.020,120.2300,119.2500,119.940,42246245.0,0.47,1.0,114.466302,114.666584,113.731932,114.390004,42246245.0
2015-02-04,118.500,120.5100,118.3090,119.560,70149743.0,0.00,1.0,112.575496,114.485004,112.394045,113.582500,70149743.0
2015-02-03,118.500,119.0900,117.6100,118.650,51915749.0,0.00,1.0,112.575496,113.135998,111.729992,112.717996,51915749.0
2015-02-02,118.050,119.1700,116.0800,118.630,62739100.0,0.00,1.0,112.147994,113.211998,110.276485,112.698996,62739100.0
2015-01-30,118.400,120.0000,116.8500,117.160,83745461.0,0.00,1.0,112.480495,114.000502,111.007989,111.302490,83745461.0
2015-01-29,116.320,119.1900,115.5600,118.900,84436432.0,0.00,1.0,110.504486,113.230998,109.782483,112.955497,84436432.0
2015-01-28,117.625,118.1200,115.3100,115.310,146477063.0,0.00,1.0,111.744242,112.214494,109.544982,109.544982,146477063.0
2015-01-27,112.420,112.4800,109.0300,109.140,95568749.0,0.00,1.0,106.799470,106.856470,103.578956,103.683456,95568749.0
2015-01-26,113.740,114.3626,112.8000,113.100,55614979.0,0.00,1.0,108.053476,108.644948,107.160472,107.445473,55614979.0
2015-01-23,112.300,113.7500,111.5300,112.980,46464828.0,0.00,1.0,106.685470,108.062976,105.953966,107.331473,46464828.0
2015-01-22,110.260,112.4700,109.7200,112.400,53796409.0,0.00,1.0,104.747461,106.846970,104.234459,106.780470,53796409.0
2015-01-21,108.950,111.0600,108.2700,109.550,48575897.0,0.00,1.0,103.502956,105.507464,102.856953,104.072958,48575897.0
2015-01-20,107.840,108.9667,106.5000,108.720,49899907.0,0.00,1.0,102.448451,103.518821,101.175445,103.284455,49899907.0
2015-01-16,107.030,107.5800,105.2000,105.990,78513345.0,0.00,1.0,101.678948,102.201450,99.940440,100.690943,78513345.0
2015-01-15,110.000,110.0600,106.6600,106.820,60013996.0,0.00,1.0,104.500460,104.557460,101.327446,101.479447,60013996.0
2015-01-14,109.040,110.4900,108.5000,109.800,48956588.0,0.00,1.0,103.588456,104.965962,103.075454,104.310459,48956588.0
2015-01-13,111.430,112.8000,108.9100,110.220,67091928.0,0.00,1.0,105.858966,107.160472,103.464955,104.709461,67091928.0
2015-01-12,112.600,112.6300,108.8000,109.250,49650790.0,0.00,1.0,106.970471,106.998971,103.360455,103.787957,49650790.0
2015-01-09,112.670,113.2500,110.2100,112.010,53315099.0,0.00,1.0,107.036971,107.587974,104.699961,106.409968,53315099.0
2015-01-08,109.230,112.1500,108.7000,111.890,59364547.0,0.00,1.0,103.768957,106.542969,103.265455,106.295968,59364547.0
2015-01-07,107.200,108.2000,106.6950,107.750,40105934.0,0.00,1.0,101.840448,102.790453,101.360696,102.362951,40105934.0
2015-01-06,106.540,107.4300,104.6300,106.260,65797116.0,0.00,1.0,101.213446,102.058949,99.398938,100.947444,65797116.0
2015-01-05,108.290,108.6500,105.4100,106.250,64285491.0,0.00,1.0,102.875953,103.217954,100.139941,100.937944,64285491.0
2015-01-02,111.390,111.4400,107.3500,109.330,53204626.0,0.00,1.0,105.820966,105.868466,101.982949,103.863957,53204626.0